  ---
- name: Update Windows OS
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: Ensure Windows updates are installed
      win_updates:
        category_names:
          - SecurityUpdates
          - UpdateRollups
          - CriticalUpdates
        state: installed
      register: update_result
 
    - name: Reboot if required by updates
      win_reboot:
      when: update_result.reboot_required
 
    - name: Wait for system to come back online after reboot
      wait_for_connection:  
        timeout: 300
 
    # Add additional tasks if needed for post-update configurations
 
- name: Post-Update Configuration
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: Your post-update tasks here
      # Add tasks for any additional configurations needed after the update
