name: CI Workflow
 
on: [push, pull_request]
 
jobs:
  ansible-ci:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
 
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
 
    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible
      continue-on-error: true
 
    - name: Run Ansible Playbooks
      run: ansible-playbook firstaction.yml
      continue-on-error: true
 
  file-check-ci:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
 
    - name: Check YAML/JSON files
      run: |
        find . -name '*.yml' -type f -exec yamllint {} +
        find . -name '*.json' -type f -exec jsonlint -q {} \;
      continue-on-error: true
